### PR TITLE
New BG which is a little less distractable

### PR DESCRIPTION
**Pull request by harsh242**
bg

### CODE REVIEW

**Comment by manangouhari** [comment]
There was another BG that I remember seeing when Ayuush shared his screen. 
It was a similar concept to this one, but had red and blue in it. 

Can you find that BG please?

**Comment by harsh242** [comment]
image

@manangouhari 
Aayush presented this one 
image

**Comment by manangouhari** [comment]
> image
> 
> @manangouhari 
> Aayush presented this one 
> image
> 

Yep, this one looks much cooler to me!

**Comment by harsh242** [comment]
The below one or the upper one?

**Comment by manangouhari** [comment]
> The below one or the upper one?

Below one. It adds more focus to the bot.

**Comment by harsh242** [comment]
Got it.

**Pull request closed without merging**
