### PR TITLE
alt approach implemented

### PR DESCRIPTION
**Pull request by manangouhari**
Modifies the approach taken by the twitter bot to optimise API calls and make the bot more reliable.

Tradeoff is, the images it uses can sometimes be of poor quality.

Q) How're the screenshots being generated now?
A) Uses `node-html-to-image` library to put the `displayUri` from token's metadata on top of a bg to generate the image.

Q) Why do we still need to keep a nodejs server running when we're not using it for screenshots anymore?
A) To deploy a constantly running script on render, otherwise it times out and fails.

### CODE REVIEW

**Comment by bhaskarSingh** [comment]
Closing the PR in favor of current working implementation.

**Comment by manangouhari** [comment]
> Closing the PR in favor of current working implementation.

Imo, this approach is much more dependable because of how we're taking the screenshot.

**Comment by bhaskarSingh** [comment]
@manangouhari  Yes, you are right. Please go ahead and merge this approach and remove the current implementation.

**Review by bhaskarSingh — APPROVED** [review]

**Comment by harsh242** [comment]
@manangouhari can you change the bg image😅, it's using the particle one aka bg.jpg
Instead, the correct one is bg.jpeg.

**Pull request merged**
